### PR TITLE
Use API Blueprint for documentation and include aglio generation

### PR DESCRIPTION
**Pull request by ArthurHoaro**
I've rewritten the API doc using the [API Blueprint](https://apiblueprint.org/) specification, including @nodiscc proposition from #1.

I've also added the [aglio](https://github.com/danielgtaylor/aglio) HTML generation for more readability.
Note that the HTML generation is a piece of cake, and could easily be added in the makefile later:

```
npm install -g aglio
aglio -i api-documentation.md -o api-documentation.html
```

Any feedback appreciated.

### CODE REVIEW

**Comment by virtualtam** [comment]
Is it possible to automate HTML generation and hosting? This could be as simple as creating a [GH Pages](https://pages.github.com/) project site for the API and switching to a `gh-pages` branch on this repo.

**Comment by ArthurHoaro** [comment]
I never used GH pages, but Travis supports NodeJS, so I guess it is possible.

**Comment by virtualtam** [comment]
Yup, this way we can:
- push Markdown API docs to `master`
- let Travis generate the static HTML and push it to `gh-pages`
- profit!

**Comment by kalvn** [comment]
I didn't know this API Blueprint + aglio process but it looks good.

I already used [RAML](http://raml.org/) + [raml2html](https://github.com/raml2html/raml2html) generators but I don't know which one can be considered as the most "standard".

**Comment by ArthurHoaro** [comment]
I've used swagger which looks similar (YAML syntax). However, I was looking for something based on Markdown, to be coherent with Shaarli's documentation.

**Pull request merged**
